language: go

go:
  - 1.13.x

addons:
  apt:
    packages:
      - rpm

install:
  - make configure

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
